LINE_1_CHECK = set([1,2,3])
LINE_2_CHECK = set([4,5,6])
LINE_3_CHECK = set([7,8,9])
COLUMN_1_CHECK = set([1,4,7])
COLUMN_2_CHECK = set([2,5,8])
COLUMN_3_CHECK = set([3,6,9])
DIAGONAL_1_CHECK = set([1,5,9])
DIAGONAL_2_CHECK = set([3,5,7])

POSSIBILITIES = [
    LINE_1_CHECK, 
    LINE_2_CHECK, 
    LINE_3_CHECK, 
    COLUMN_1_CHECK, 
    COLUMN_2_CHECK, 
    COLUMN_3_CHECK, 
    DIAGONAL_1_CHECK, 
    DIAGONAL_2_CHECK
]
